### ISSUE TITLE
Please tell me how to generate the two keys open and closed as it does TSL

### ISSUE THREAD

**Issue by StasToken** [Jens-G/haxe-crypto#12]
Please tell me how to generate the two keys open and closed as it does TSL ( I apologize in advance if I ask a stupid question just don't have the brains to understand it... )

**Comment by soywiz** [comment]
I don't remember. Since I'm not maintaining this project anymore. Maybe it is not possible yet? If it is. It should be a test. Of course if anybody else knows why. Please tell him. Also even if not maintaining by myself the project anymore, i accept PRs and update haxelib.
