### ISSUE TITLE
IPad Problem

### ISSUE THREAD

**Issue by barisyild** [Jens-G/haxe-crypto#16]
1th try

> import com.hurlant.crypto.pad.IPad;
> 
> 
> ...
> var data : ByteArray = Base64.decodeToByteArray(encryptedValue);
> var pad:IPad = new PKCS5();
> var mode : ICipher = Crypto.getCipher("des-ecb", passkey, pad);
> pad.setBlockSize(mode.getBlockSize());
> mode.decrypt(data);

**Error:(41, 9) com.hurlant.crypto.symmetric.PKCS5 should be com.hurlant.crypto.pad.IPad**

2nd try

> import com.hurlant.crypto.symmetric.IPad;
> 
> ...
> var data : ByteArray = Base64.decodeToByteArray(encryptedValue);
> var pad:IPad = new PKCS5();
> var mode : ICipher = Crypto.getCipher("des-ecb", passkey, pad);
> pad.setBlockSize(mode.getBlockSize());
> mode.decrypt(data);

**Error:(43, 67) com.hurlant.crypto.symmetric.IPad should be Null<com.hurlant.crypto.pad.IPad>**

**Comment by Jens-G** [comment]
Since you have a test case ... possible to send a patch?

**Comment by Jens-G** [comment]
```
package;

import com.hurlant.crypto.Crypto;
import com.hurlant.crypto.encoding.binary.Base64;
import com.hurlant.crypto.pad.IPad;
import com.hurlant.crypto.pad.PKCS5;
import com.hurlant.crypto.symmetric.ICipher;
import com.hurlant.util.Base64;
import com.hurlant.util.ByteArray;

class Main
{
    static public function main()
    {
		var data : ByteArray = Base64.decodeToByteArray("encryptedValue");
		var pad:IPad = new PKCS5();
		var passkey : ByteArray = new ByteArray();
		var mode : ICipher = Crypto.getCipher("des-ecb", passkey, pad);
		pad.setBlockSize(mode.getBlockSize());
		mode.decrypt(data);
    }
}

```

No compiler errors.
