### ISSUE TITLE
invalid js import on sys platforms in 0.0.7 (curent haxelib)

### ISSUE THREAD

**Issue by Jens-G** [Jens-G/haxe-crypto#17]
The SecureRandom.hx file in the current 0.0.7 haxelib version does not restrict one js import to js platforms, therefore it fails with cpp targets. Although the fix is easy 1), I wonder if you plan to update the package on haxelib to something more recent?

1) just surround the import with #if js ... #end, already fixed in current master

**Comment by soywiz** [comment]
I'm not maintaining this library anymore, but if you can make a PR I can merge it 👍
