### ISSUE TITLE
Would JWT fit into this library?

### ISSUE THREAD

**Issue by ianharrigan** [Jens-G/haxe-crypto#21]
Hi!

So im wondering if JWT would be useful for this library? I havent written it yet, but i plan to, and just wondering if you would consider it a good fit for "haxe-crypto" or if i should roll out my own library that uses haxe-crypto?

Thanks!
Ian

**Comment by flashultra** [comment]
Hi Ian, 
 About JWT , I think this library for Haxe  https://github.com/kevinresol/jsonwebtoken is maybe what you looking for.

**Comment by ianharrigan** [comment]
Oh, nice thanks! I found a different one that didnt support RSA, but it looks like this one might - ill check it out a little deeper.

Thanks!

**Comment by Jens-G** [comment]
Not sure. From my feelings JWT is one abstraction level up ... it _uses_ cryptography to achive some outcome.
