### ISSUE TITLE
BigInteger.modPowInt takes a very long time

### ISSUE THREAD

**Issue by chipshort** [Jens-G/haxe-crypto#4]
When trying to use RSA, I found that BigInteger seems to take quite a long time for this number:

``` haxe
var i = new com.hurlant.math.BigInteger ("2a4b018de491aa4adccd3d2ca66c623f37a08b82b2bbc38cff2b2f95d0e35fe8f19061ce8d705737af455f75e5b78aab856412ed5d8a0ce510068656c6c6f");

haxe.Timer.measure (function () {
    i.modPowInt (65537, new com.hurlant.math.BigInteger ("c4e3f7212602e1e396c0b6623cf11d26204ace3e7d26685e037ad2507dce82fc28f2d5f8a67fc3afab89a6d818d1f4c28cfa548418bd9f8e7426789a67e73e41"));
});
```

It almost took 5 minutes on my machine, which seems quite long to me.
This is the portion that took most of the time, as qd seems to be very large:
https://github.com/soywiz/haxe-crypto/blob/master/src/com/hurlant/math/BigInteger.hx#L602-L605

Is this normal? It makes RSA encryption incredibly slow, as it is performed on each block.

I also noticed that something in PEM.readRSAPrivateKey is broken, it only throws an exception (even with the code from the unit tests).

**Comment by Jens-G** [comment]
I get 

1a9f0a9e6e2a5074e53b7b5eccf3286ec8e8efc268191e1077326ed9e3a8dada1438512d87cf6843f24e28ca02493d8b829fded0c7dc272cf6144c7113688b3c451d4f2931a12b119513141fd32819cc0a58550a68572e76cd1ef2a0d4ac0449b187e69006932c69d11f55e2912fe1ab628552028517226e8b91fbb909528972a0a284b3d187e7813811814010be5d5fae873aa60973e64d94bf9086b87e6b8a000b6ecccc2619facfa866bbaad38d444f1bba3976e04ec49434118b491a1f45cf7f1651cc673ab2ebcbaace271517d1fd6eaf93671699a9c497c935c1860cbb237078cf60da408fe6ffc7fd5567353309ba0dd3e2410e9d12da61bed9fb84b7ce867c7090aef9cd1bfb7fe0f54de2dfaecb216821e55f2207d4f82115a4f1ca7a65df068c8808afee022f0ba1ec6152dac698a939b321b1605109efe043ea988ffcc3f28c0e463b674ed8ae5fe63db13779b0b502de1c1a14c269c9f1f1342aff0d6de7508e347b9cf27684845d654a35153474e2778d4b3bd620846099561bfe8ec7926ce73638

in  0.006699999988079075s

I used JS target

**Comment by Jens-G** [comment]
> https://github.com/soywiz/haxe-crypto/blob/master/src/com/hurlant/math/BigInteger.hx#L602-L605

All I can see there is some debug trace, which is also inactive by default unless yo tell the function to enable debug. Mmmh.

**Comment by chipshort** [comment]
@Jens-G This is almost 7 years old and the link was not a permalink, so obviously it's outdated.
At the time, it was pointing to this code: https://github.com/Jens-G/haxe-crypto/blob/7ee43553ae240f28807ff378750d334ec222dba5/src/com/hurlant/math/BigInteger.hx#L602-L605

Not sure what target I was using back then.
