### ISSUE TITLE
Invalid operation (|)

### ISSUE THREAD

**Issue by hamaluik** [Jens-G/haxe-crypto#6]
On Windows 8.1, neko 2.1, I'm trying to use the SHA hashing functions (as part of pbkdf2), however I keep getting an exception:

```
Invalid operation (|)
```

coming from [SHA1.hx#L31](https://github.com/soywiz/haxe-crypto/blob/b34bae1a48d7ceb2815fb3d9195938ae7a8d8e5a/src/com/hurlant/crypto/hash/SHA1.hx#L31).

I got around it by modifying a local copy of pbkdf2 to use the `haxe.crypto.Hmac` class instead of the one packaged here.

**Comment by fulopm** [comment]
The bug is affecting me too when trying to use SHA classes.

**Comment by Jens-G** [comment]
```
package;

import com.hurlant.crypto.hash.SHA1;
import com.hurlant.util.ByteArray;
import haxe.io.Bytes;

class Main 
{
	public static function main() 
	{
		var hasher = new SHA1();
		var data : ByteArray = new ByteArray();
		data.writeUTFBytes("Test");
		var hash : Bytes = hasher.hash(data);
		trace('hash = ${hash.toHex()}');
	}
}
```

gives

```
src/Main.hx:15: hash = 640ab2bae07bedc4c163f679a746f7ab7fb5d1fa
```
